[package]
name = "textencoding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "hex"
harness = false

[dependencies]

[dev-dependencies]
claim = "0.5"
criterion = "0.3"
